### ISSUE TITLE
Move function problem 

### ISSUE THREAD

**Issue by Subucc** [xvol/bezmouse#4]
```
>>> mouse.move([(200, 200), (400, 400)])
Traceback (most recent call last):
  File "e:\Files\Programming\Python\Smaller Projects\Better Chess Bot\sdk.py", line 88, in <module>
    mouse.move((300, 400, 500))
  File "e:\Files\Programming\Python\Smaller Projects\Better Chess Bot\mouse.py", line 207, in move
    outfile = open(CWD + '/tmp/' + fname, 'w')
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\Files\\Programming\\Python\\Smaller Projects\\Better Chess Bot/tmp/mouse.sh'
```

**Comment by Subucc** [comment]
I didn't see that i need linux for that ;//
